name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "*/15 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "bahim22-patch-*"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: bahim22
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
          plugin_code: yes
          plugin_code_days: 500
          plugin_code_languages: JavaScript, python, Juypter Notebooks, Bash, Markdown
          plugin_code_lines: 12
          plugin_code_load: 50
          plugin_code_visibility: public
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: Scss, less
          plugin_languages_indepth: yes
          plugin_languages_indepth_custom: Bahim22/work, bahim22/engage-flower
          plugin_languages_limit: 8
          plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          #plugin_skyline: yes
          ##plugin_skyline_frames: 60
          #plugin_skyline_quality: 0.5
          #plugin_skyline_year: 2023
           #   plugin_skyline_settings: {
            #  "url": "https://skyline.github.com/${login}/${year}",
          #"ready": "[...document.querySelectorAll('span')].map(span => span.innerText).includes('Share on Twitter')",
         # "wait": 1,
         # "hide": "button, footer, a"
        #  }
          repositories_batch: 25
