name: Metrics
on:
  schedule: [{cron: "15 */2 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "bahim22-patch-*"]}
  pull_request: {branches: ["bahim22-patch-1", "bahim22-pr-2"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: development
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          output_action: pull-request
          # committer_branch: bahim22-patch-1
          committer_message: "cron scheduled: update metrics"
          token: ${{ secrets.METRICS_TOKEN }}
          clean_workflows: timed-out, cancelled
          retries: 0
          retries_delay: 150
          retries_output_action: 0
          retries_delay_output_action: 150
          optimize: css, xml # svg
          user: Bahim22
          template: classic
          base: header, activity, repositories, metadata
          base_indepth: yes
          commits_authoring: bahim22, Dionysus, Hima Dionysus Balde
          config_octicon: yes
          config_presets: "@lunar-red"
          config_timezone: America/New_York
          plugin_code: yes
          plugin_code_days: 365
          plugin_code_languages: javaScript, typescript, python, Jupyter Notebook, shell, Bash, Markdown, powershell
          plugin_code_lines: 12
          plugin_code_load: 50
          plugin_code_visibility: public
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 10
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: scss, less
          plugin_languages_indepth: yes
          plugin_languages_indepth_custom: Bahim22/work, bahim22/engage-flower
          plugin_languages_limit: 10
          plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 2
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_url: "https://ppu-hd-fs.vercel.app"
          plugin_screenshot: yes
          plugin_screenshot_background: yes
          plugin_screenshot_mode: image
          plugin_screenshot_selector: header
          plugin_screenshot_title: Screenshot
          plugin_screenshot_url: "https://himabalde.netlify.app"
          plugin_screenshot_viewport: | 
            {
            "width": 640, "height": 640 
            }
          plugin_screenshot_wait: 2000
          plugin_skyline: yes
          plugin_skyline_frames: 120
          plugin_skyline_quality: 0.75
          plugin_skyline_settings: | 
            { 
              "url": "https://skyline.github.com/${login}/${year}", 
              "ready": "[...document.querySelectorAll('span')].map(span => span.innerText).includes('Share on Twitter')", 
              "wait": 1, 
              "hide": "button, footer, a"
            }
          plugin_skyline_year: 2023
          repositories_batch: 25
