# Visit https://github.com/lowlighter/metrics#-documentation
# https://github.com/lowlighter/metrics/blob/master/source/plugins/core/README.md#-configuring-output-action
name: Metrics Workflow
on:
  # Schedule updates (each hour)
  schedule: [{cron: "50 */1 * * 4-0"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "bahim22-patch-*"]}
  pull_request:
    branches:
    - master
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      # use output_action: pull-request to make the action open a new pull request |
      # and push changes from the same run on it. #
      #- uses: lowlighter/metrics@latest
       # with:
        #  filename: my-metrics-0.svg
         # output_action: pull-request
     # - uses: lowlighter/metrics@latest
       # with:
        #  filename: my-metrics-1.svg
         # output_action: pull-request-merge
      # Use output_action: commit to make the action directly push changes to committer_branch with a commit.
      # push output to metrics-renders branch rather than the default branch
      - uses: lowlighter/metrics@latest
        with:
          output_action: commit
          committer_branch: metrics-renders
          committer_message: "cron scheduleed: update metrics"
          token: ${{ secrets.METRICS_TOKEN }}
          # retry render $ output action <= 3 (wait 2.5 m between each fail)
          retries: 3
          retries_delay: 150
          retries_output_action: 3
          retries_delay_output_action: 150
          optimize: css, xml # svg
          # experimental_features: --optimize-svg
          # Options
          user: Bahim22
          template: classic
          base: header, activity, repositories, metadata
          base_indepth: yes
          commits_authoring: .user/.login
          config_octicon: yes
          config_presets: "@lunar-red"
          config_timezone: America/New_York
          plugin_code: yes
          plugin_code_days: 500
          plugin_code_languages: javaScript, python, Jupyter Notebook, Bash, Markdown
          plugin_code_lines: 12
          plugin_code_load: 50
          plugin_code_visibility: public
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: scss, less
          plugin_languages_indepth: yes
          plugin_languages_indepth_custom: Bahim22/work, bahim22/engage-flower
          plugin_languages_limit: 8
          plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 2
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_pagespeed_token: ${{ secrets.PAGESPEED }}
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_url: "https://ppu-hd-fs.vercel.app"
          plugin_screenshot: yes
          plugin_screenshot_background: yes
          plugin_screenshot_mode: image
          plugin_screenshot_selector: body
          plugin_screenshot_title: Screenshot
          plugin_screenshot_url: https://himabalde.netlify.app
          plugin_screenshot_viewport: | 
            {
            "width": 1280, "height": 1280 
            }
          plugin_screenshot_wait: 2000
          plugin_skyline: yes
          plugin_skyline_frames: 120
          plugin_skyline_quality: 0.75
          plugin_skyline_settings: | 
            { 
              "url": "https://skyline.github.com/${login}/${year}", 
              "ready": "[...document.querySelectorAll('span')].map(span => span.innerText).includes('Share on Twitter')", 
              "wait": 1, 
              "hide": "button, footer, a"
            }
          plugin_skyline_year: 2023
          repositories_batch: 25
          config_padding: 0, 10 + 8%
          # base: header
          #  extras_js: |
                # document.querySelectorAll("h2")?.forEach(h2 => h2.remove())
             #extras_css: |
             #  h2 {
                 #color: red;
              #    }
