name: Metrics
on:
  schedule: [{cron: "0 8 * * 6"}]
  workflow_dispatch:
  push: {branches: ["master", "bahim22-patch-*"]}
  # pull_request: {branches: ["bahim22-patch-*", "bahim22-pr-*"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: development
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          output_action: pull-request
          filename: metrics2.svg
          committer_message: "Scheduled: update metrics"
          token: ${{ secrets.METRICS_TOKEN }}
          clean_workflows: timed-out, cancelled
          optimize: css, xml, svg
          user: Bahim22
          template: classic
          base: header, activity, repositories, metadata
          base_indepth: yes
          commits_authoring: bahim22, Dionysus, Hima Dionysus Balde, 78245175+bahim22@users.noreply.github.com
          config_octicon: yes
          config_presets: "@lunar-red"
          config_timezone: America/New_York
          plugin_code: yes
          plugin_code_days: 365
          plugin_code_languages: javascript, typescript, python, shell, Bash, HTML, Markdown, powershell, json, XML
          plugin_code_lines: 12
          plugin_code_load: 50
          plugin_code_visibility: public
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 20
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: scss, less
          plugin_languages_indepth: yes
          plugin_languages_limit: 15
          plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 10
          plugin_lines_repositories_limit: 10
          plugin_lines_sections: base
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_url: "https://ppu-hd-fs.vercel.app"
          repositories_batch: 25
