name: Metrics
on:
  schedule: [{cron: "15 */12 * * *"}]
  workflow_dispatch:
  # push: {branches: ["master", "bahim22-patch-*"]}
  # pull_request: {branches: ["bahim22-patch-1", "bahim22-pr-2"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: Dev1
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          #output_action: pull-request
          #filename: metrics1.svg
          #committer_message: "PR Scheduled: update metrics"
          #committer_branch: metrics-renders
          token: ${{ secrets.METRICS_TOKEN }}
          #output_action: pull-request-merge
          clean_workflows: timed-out, cancelled
          optimize: css, xml, svg
          user: Bahim22
          template: classic
          base: header, activity, repositories, metadata
          base_indepth: yes
          commits_authoring: bahim22, Dionysus, Hima Dionysus Balde, 78245175+bahim22@users.noreply.github.com
          config_octicon: yes
          config_presets: "@lunar-red"
          config_timezone: America/New_York
          plugin_code: yes
          plugin_code_days: 180
          plugin_code_languages: javascript, typescript, python, Jupyter Notebook, shell, Bash, HTML, Markdown, powershell, json
          plugin_code_lines: 12
          plugin_code_load: 50
          plugin_code_visibility: public
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 10
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: scss, less
          plugin_languages_indepth: yes
          plugin_languages_indepth_custom: Bahim22/work, bahim22/engage_flower
          plugin_languages_limit: 10
          plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_load: 100
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 6
          plugin_lines_repositories_limit: 8
          plugin_lines_sections: base
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_url: "https://ppu-hd-fs.vercel.app"
          repositories_batch: 25
          output_action: commit
          filename: metrics2.svg
          committer_branch: metrics_commit
          committer_message: "chore: update metrics"
          #plugin_screenshot: yes
          #plugin_screenshot_background: yes
          #plugin_screenshot_mode: image
          #plugin_screenshot_selector: body
          #plugin_screenshot_title: Screenshot
          #plugin_screenshot_url: "https://happy-ocean-0d2a3c60f.azurestaticapps.net/"
          #plugin_screenshot_viewport: | 
            #{
            #"width": 640, "height": 640 
            #}
          #plugin_screenshot_wait: 3000
